### ISSUE TITLE
publish server and admin to railway using github actions

### ISSUE THREAD

**Issue by zeyuri** [zeyuri/pwr-store#2]
Using a infra provider zero config setup like railway is awesome when boostraping and when you don't need to customize your workflow.

But as soon as you have to do advanced things you have to move out.

In this case what we're gonna do is use github actions + turborepo + docker to create this flow.

Today the flow is very simple:

1. we push new code into the main branch
2. this kicks a deployment on railway
3. In the deploy railway build the apps and then publish things

The github action job will looks something like this:

```
name: CI
 
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
          cache: pnpm

      - name: Audit dependencies
        run: pnpm audit --audit-level critical

      - name: Install dependencies
        run: pnpm install

      - name: Deploy Server
        if: github.ref == 'refs/heads/main'
        run: pnpm run railway up --service server
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

```

The trick part will be the Dockerfile. The idea will be to follow this guide https://turbo.build/repo/docs/handbook/deploying-with-docker
